apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: "v1"
    served: true
    storage: false
  - name: "v1alpha1"
    served: true
    storage: true
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: webhook-service
        namespace: default
        path: "/crdconvert"
        port: 9443
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
